14/circles/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    get :blogs, on: :member
  end
  
  resources :sessions

  resources :blogs

  namespace :admin do
    root 'users#index'

    resources :users do
      collection do
        get :search
      end
    end
  end

end

14/circles/app/models/blog.rb
class Blog < ActiveRecord::Base

  validates :title, presence: { message: "标题不能为空" }
  validates :content, presence: { message: "内容不能为空" }
  validates :user_id, presence: { message: "用户不能为空" }

  belongs_to :user
  has_many :blogs_tags, class_name: "BlogsTags"
  has_many :tags, through: :blogs_tags

end

14/circles/app/models/blogs_tags.rb
class BlogsTags < ActiveRecord::Base

  self.table_name = 'blogs_tags'

  validates_uniqueness_of :blog_id, scope: [:tag_id]

  belongs_to :blog
  belongs_to :tag

end

14/circles/app/models/tag.rb
class Tag < ActiveRecord::Base

  validates :title, uniqueness: { message: "标签已存在" }

  has_many :blogs_tags, class_name: "BlogsTags"
  has_many :blogs, through: :blogs_tags

end

14/circles/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: { message: "用户名不能为空" }
  validates :username, uniqueness: { message: "用户名已存在" }
  validates :password, presence: { message: "密码不能为空" }
  validates :password, length: { minimum: 6, message: "密码长度最短为6位" }

  has_many :blogs
  has_many :public_blogs, -> { where(is_public: true) },
    class_name: "Blog"

end

14/circles/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'admin'

end

14/circles/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def search
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc").where(["username like ?", "%#{params[:username]}%"])

    render action: :index
  end

end

14/circles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Concerns::UserSession
  
  private
  def auth_user
    unless logged_in?
      flash[:notice] = "请登录"
      redirect_to new_session_path
    end
  end

end

14/circles/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :auth_user, except: [:index, :show]

  def index
    @blogs = Blog.page(params[:page] || 1).per_page(params[:per_page] || 10).
      order("id desc").where(is_public: true)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_attrs)
    if @blog.save
      update_tags

      flash[:notice] = "博客创建成功"
      redirect_to blogs_path
    else
      flash[:notice] = "博客创建失败"
      render action: :new
    end
  end

  def show
    @blog = Blog.find params[:id]
  end

  def edit
    @blog = Blog.find params[:id]
    render action: :new
  end

  def update
    @blog = Blog.find params[:id]
    @blog.attributes = blog_attrs
    if @blog.save
      @blog.tags.destroy_all
      update_tags

      flash[:notice] = "博客更新成功"
      redirect_to blogs_path
    else
      flash[:notice] = "博客更新失败"
      render action: :new
    end
  end

  private
  def blog_attrs
    params.require(:blog).permit(:title, :content, :is_public)
  end

  def update_tags
    params[:tags].split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag

      @blog.tags << one_tag
    end
  end

end

14/circles/app/controllers/concerns/user_session.rb
module Concerns

  module UserSession
    def self.included base
      base.class_eval do
        helper_method :logged_in?
        helper_method :current_user
      end
    end

    def signin_user user
      session[:user_id] = user.id
    end

    def logout_user
      session[:user_id] = nil
    end

    def logged_in?
      !!session[:user_id]
    end

    def current_user
      if logged_in?
        @current_user ||= User.find(session[:user_id])
      else
        nil    
      end
    end

  end


end

14/circles/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user
      signin_user @user
      
      render json: {
        status: 'ok',
        msg: {
          redirect_url: root_path
        }
      }
    else
      render json: {
        status: 'error',
        msg: "用户名或密码不正确"
      }
    end
  end

  def destroy
    logout_user
    
    flash[:notice] = "退出成功"
    redirect_to root_path
  end
end

14/circles/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :auth_user, only: [:index]

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_attrs)
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  def blogs
    @blogs = current_user.blogs.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  private
  def user_attrs
    params.require(:user).permit(:username, :password)
  end

end

14/circles/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @user = if session[:user_id]
      User.find session[:user_id]
    else
      nil
    end
  end

end

14/circles/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

14/circles/app/helpers/application_helper.rb
module ApplicationHelper
end

14/circles/app/helpers/blogs_helper.rb
module BlogsHelper
end

14/circles/app/helpers/welcome_helper.rb
module WelcomeHelper
end

14/circles/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circles后台管理</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Circles后台管理
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= admin_users_path %>">用户管理</a>
              </li>

              <% if logged_in? %>
                <li><%= link_to "#{current_user.username}, 退出", session_path(session[:user_id]), method: 'delete' %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

14/circles/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circles</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Circles
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= users_path %>">用户</a>
              </li>

              <% if logged_in? %>
                <li><%= link_to "#{current_user.username}, 退出", session_path(session[:user_id]), method: 'delete' %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>

              <li><%= link_to "博客", blogs_path %></li>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :javascripts %>
  </body>
</html>