21/circles/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users do
    get :blogs, on: :member
  end
  
  resources :sessions

  resources :blogs

  namespace :admin do
    root 'users#index'

    resources :users do
      collection do
        get :search
      end
    end
  end

end

21/circles/app/models/blog.rb
class Blog < ActiveRecord::Base

  validates :title, presence: { message: "标题不能为空" }
  validates :content, presence: { message: "内容不能为空" }
  validates :user_id, presence: { message: "用户不能为空" }

  belongs_to :user
  has_many :blogs_tags, class_name: "BlogsTags"
  has_many :tags, through: :blogs_tags


  def tags_string= one_tags
    self.tags.destroy_all

    one_tags.split(',').each do |tag|
      one_tag = Tag.find_by(title: tag)
      one_tag = Tag.new(title: tag) unless one_tag

      self.tags << one_tag
    end
  end

end

21/circles/app/models/blogs_tags.rb
class BlogsTags < ActiveRecord::Base

  self.table_name = 'blogs_tags'

  validates_uniqueness_of :blog_id, scope: [:tag_id]

  belongs_to :blog
  belongs_to :tag

end

21/circles/app/models/tag.rb
class Tag < ActiveRecord::Base

  validates :title, uniqueness: { message: "标签已存在" }

  has_many :blogs_tags, class_name: "BlogsTags"
  has_many :blogs, through: :blogs_tags

end

21/circles/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: { message: "用户名不能为空" }
  validates :username, uniqueness: { message: "用户名已存在" }

  has_many :blogs
  has_many :public_blogs, -> { where(is_public: true) },
    class_name: "Blog"

  has_one :latest_blog,  -> { order("id desc") }, class_name: :Blog

  before_save :update_username

  # attr_accessor :old_password
  attr_accessor :password
  attr_accessor :password_confirmation

  validate :validate_password, on: :create
  before_create :set_password

  def self.authenticate username, password
    user = find_by(username: username)
    if user and user.valid_password?(password)
      user
    else
      nil
    end
  end

  def valid_password? password
    self.crypted_password == Digest::SHA256.hexdigest(password + self.salt)
  end

  private
  def validate_password
    if self.password.blank?
      self.errors.add(:password, "密码不能为空")
      return false
    end

    unless self.password == self.password_confirmation
      self.errors.add(:password_confirmation, "密码不一致")
      return false
    end

    return true
  end

  def set_password
    self.salt = Time.now.to_i
    self.crypted_password = Digest::SHA256.hexdigest(self.password + self.salt)
  end

  def update_username
    self.username = self.username.downcase
  end

end

21/circles/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'admin'

end

21/circles/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def search
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc").where(["username like ?", "%#{params[:username]}%"])

    render action: :index
  end

end

21/circles/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Concerns::UserSession
  
  private
  def auth_user
    unless logged_in?
      flash[:notice] = "请登录"
      redirect_to new_session_path
    end
  end

end

21/circles/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_filter :auth_user, except: [:index, :show]

  def index
    @blogs = Blog.page(params[:page] || 1).per_page(params[:per_page] || 10).
      order("id desc").where(is_public: true).includes(:tags, :user)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_attrs)
    if @blog.save
      flash[:notice] = "博客创建成功"
      redirect_to blogs_path
    else
      flash[:notice] = "博客创建失败"
      render action: :new
    end
  end

  def show
    @blog = Blog.find params[:id]
  end

  def edit
    @blog = Blog.find params[:id]
    render action: :new
  end

  def update
    @blog = Blog.find params[:id]
    @blog.attributes = blog_attrs
    if @blog.save
      flash[:notice] = "博客更新成功"
      redirect_to blogs_path
    else
      flash[:notice] = "博客更新失败"
      render action: :new
    end
  end

  private
  def blog_attrs
    params.require(:blog).permit(:title, :content, :is_public, :tags_string)
  end

end

21/circles/app/controllers/concerns/user_session.rb
module Concerns

  module UserSession
    def self.included base
      base.class_eval do
        helper_method :logged_in?
        helper_method :current_user
      end
    end

    def signin_user user
      session[:user_id] = user.id
    end

    def logout_user
      session[:user_id] = nil
    end

    def logged_in?
      !!session[:user_id]
    end

    def current_user
      if logged_in?
        @current_user ||= User.find(session[:user_id])
      else
        nil    
      end
    end

  end


end

21/circles/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      signin_user @user
      
      render json: {
        status: 'ok',
        msg: {
          redirect_url: root_path
        }
      }
    else
      render json: {
        status: 'error',
        msg: "用户名或密码不正确"
      }
    end
  end

  def destroy
    logout_user
    
    flash[:notice] = "退出成功"
    redirect_to root_path
  end
end

21/circles/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :auth_user, only: [:index]

  def index
    @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_attrs)
    if @user.save
      flash[:notice] = "注册成功，请登录"
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  def blogs
    @blogs = current_user.blogs.page(params[:page] || 1).per_page(params[:per_page] || 10)
      .order("id desc")
  end

  private
  def user_attrs
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

21/circles/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @user = if session[:user_id]
      User.find session[:user_id]
    else
      nil
    end
  end

end

21/circles/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

21/circles/app/helpers/application_helper.rb
module ApplicationHelper
end

21/circles/app/helpers/blogs_helper.rb
module BlogsHelper
end

21/circles/app/helpers/welcome_helper.rb
module WelcomeHelper
end

21/circles/app/views/blogs/_blogs.html.erb
<table class="table">
  <tr>
    <th>ID</th>
    <th>标题</th>
    <th>作者</th>
    <th></th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.id %></td>
      <td>
        <%= link_to blog.title, blog_path(blog) %> 
        <% blog.tags.each do |tag| %>
          <span class="badge"><%= tag.title %></span>
        <% end -%>
      </td>
      <td><%= blog.user.username %></td>
      <td>
        <% if blog.user == current_user %>
          <%= blog.is_public ? "显示" : "不显示" %>

          <%= link_to "编辑", edit_blog_path(blog) %>
        <% end -%>
      </td>
    </tr>
  <% end -%>
</table>

<%= will_paginate @blogs %>

21/circles/app/views/blogs/index.html.erb
<h1>博客</h1>

<div>
  <%= link_to "创建博客", new_blog_path, class: "btn btn-primary" %>
  <% if logged_in? %>
    <%= link_to "我的博客", blogs_user_path(current_user), class: "btn btn-default" %>
  <% end -%>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render 'blogs' %>
  </div>
</div>

21/circles/app/views/blogs/new.html.erb
<h1><%= @blog.new_record? ? '创建' : '编辑' %>博客</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @blog, url: (@blog.new_record? ? blogs_path : blog_path(@blog)), method: (@blog.new_record? ? :post : :put) do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @blog.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>

      <div class="form-group">
        <%= f.text_field :title, class: "form-control", placeholder: "标题" %>
      </div>

      <div class="form-group">
        <%= f.text_area :content, class: "form-control", placeholder: "内容" %>
      </div>

      <div class="form-group">
        <input type="text" name="blog[tags_string]" value="<%= @blog.tags.map(&:title).join(',') %>" /><small>标签以逗号分隔</small>
      </div>

      <div class="form-group">
        <% [[true, "显示"], [false, "不显示"]].each do |public| %>
          <input type="radio" name="blog[is_public]" value="<%= public.first %>" <%= 'checked' if @blog.is_public == public.first %> /> <%= public.last %>
        <% end -%>
      </div>      

      <%= f.submit "保存", class: "btn btn-primary" %> 
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

21/circles/app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>

<div class="row">
  <div class="col-sm-5">
    <p>作者: <%= @blog.user.username %>, <%= @blog.created_at %></p>
    <%= @blog.content %>
  </div>

  <div class="col-sm-7">
  </div>
</div>