27_BONUS/circles/config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'messages/new'

  root 'welcome#index'

  resources :users do
    get :blogs, on: :member
  end
  
  resources :sessions

  resources :blogs
  resources :messages

  namespace :admin do
    root 'users#index'

    resources :users do
      collection do
        get :search
      end
    end
  end

end

27_BONUS/circles/app/models/message.rb
class Message < ActiveRecord::Base

  validates :receiver_id, presence: { message: "收件人不能为空" }
  validates :sender_id, presence: { message: "发件人不能为空" }
  validates :content, presence: { message: "内容不能为空" }

  belongs_to :sender, class_name: :User
  belongs_to :receiver, class_name: :User

  attr_accessor :receiver_username

  validate :validate_username

  def is_read_to_s
    self.is_read ? "已读" : "未读"  
  end

  def receiver_username= username
    if user = User.find_by(username: username)
      self.receiver = user
    end
  end

  private
  def validate_username
    unless self.receiver
      self.errors.add(:receiver_username, "收件人不存在")
      false
    else
      true
    end
  end

end

27_BONUS/circles/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :auth_user

  def index
    params[:type] ||= 'inbox'
    @messages = if params[:type] == 'inbox'
      current_user.inboxes
    else
      current_user.outboxes
    end
    
    @messages = @messages.page(params[:page] || 1)
      .per_page(params[:per_page] || 10)
      .order("id desc")
  end

  def new
    @message = current_user.outboxes.new
  end

  def create
    @message = current_user.outboxes.new(params.require(:message).permit!)
    if @message.save
      flash[:notice] = "发送成功"
      redirect_to messages_path
    else
      render action: :new
    end
  end

  def show
    @message = Message.find(params[:id])
    unless @message.sender == current_user or 
      @message.receiver == current_user
      render text: "403 Forbidden"
      return
    else
      if @message.receiver == current_user
        @message.update_attribute :is_read, true
      end
    end
  end

end

27_BONUS/circles/app/helpers/messages_helper.rb
module MessagesHelper
end

27_BONUS/circles/app/views/messages/index.html.erb
<h1>私信</h1>

<div>
  <%= link_to "创建私信", new_message_path, class: "btn btn-primary" %>
</div>

<div>
  <%= link_to "收件箱", messages_path, class: "btn btn-default" %> 
  <%= link_to "发件箱", messages_path(type: 'outbox'), class: "btn btn-default" %> 
</div>
<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <tr>
        <th>ID</th>
        <th><%= params[:type] == 'inbox' ? "发件人" : "收件人" %></th>
        <th>内容</th>
        <th>已读</th>
        <th></th>
      </tr>
      <% @messages.each do |message| %>
        <tr>
          <td><%= message.id %></td>
          <td><%= params[:type] == 'inbox' ? message.sender.username : message.receiver.username %></td>
          <td><%= truncate message.content, length: 30 %></td>
          <td><%= message.is_read_to_s %></td>
          <td>
            <%= link_to "详情", message_path(message) %>
          </td>
        </tr>
      <% end -%>
    </table>

    <%= will_paginate @messages %>
  </div>
</div>

27_BONUS/circles/app/views/messages/new.html.erb
<h1>创建私信</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @message, url: messages_path, method: :post do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @message.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>

      <div class="form-group">
        <input type="text" name="message[receiver_username]" value="<%= params[:message][:receiver_username] rescue params[:receiver_username] %>" class="form-control" placeholder="收件人" />
      </div>

      <div class="form-group">
        <%= f.text_area :content, class: "form-control", placeholder: "内容" %>
      </div>

      <%= f.submit "发送", class: "btn btn-primary" %> 
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

27_BONUS/circles/app/views/messages/show.html.erb
<h1>私信</h1>

<div class="row">
  <div class="col-sm-5">
    <p>From: <%= @message.sender.username %></p>
    <p>To: <%= @message.receiver.username %></p>
    <p><%= @message.content %></p>
  </div>

  <% if @message.receiver == current_user %>
    <p>
      <%= link_to "回复", new_message_path(receiver_username: @message.sender.username) %>
    </p>
  <% end -%>
  <div class="col-sm-7">
  </div>
</div>